// products.ts
import { ref } from "vue";
import type { Product } from "~/types";

export const baseProducts = ref<Product[]>([
  {
    id: 0,
    nickname: "Digistickers",
    tooltip_nickname: "Cooler Stuff",
    drucktechnik: "Digitaldruck",
    tooltip_drucktechnik: "",
    bedruckstoff: "PVC-Folie",
    tooltip_bedruckstoff: "PVC-Folie",
    materialfarbe: "weiß",
    tootltip_materialfarbe: "weiß",
    farbigkeit: "4/4 Skala",
    tooltip_farbigkeit: "4/4 Skala: Bunt wie in Photos",
    form: "rechteckig",
    tooltip_form: "rechteckig mit spitzen Ecken",
    format_breite: 0,
    format_hoehe: 0,
    tooltip_format: "Angaben in mm.",
    traeger: "Auf Bogen",
    tooltip_traeger: "Angestanzt auf handlichen Bögen",
    klebehaftung: "Festhaftend",
    tooltip_klebehaftung:
      "Gerne bemustern wir Ihnen das gewünschte Material zum Testen der Klebehaftung",
    lieferland: "Deutschland",
    liefertermin: "1.1.1970",
    tooltip_liefertermin:
      "Kann auf Inseln abweichen. Sprechen Sie uns ggf. auf einne schnelleren Termin direkt an.",
    sorten: 1,
    auflage: 0,
    price_net: 0.0,
    price_gross: 0.0,
    image_calc_url: "/images/stickers/digisticker.webp",
    quantity: 1,
  },
  {
    id: 1,
    nickname: "Siebdruckdinger",
    tooltip_nickname: "",
    drucktechnik: "Siebdruck",
    tooltip_drucktechnik: "",
    bedruckstoff: "PVC-Folie",
    tooltip_bedruckstoff: "PVC-Folie vom Feinsten",
    materialfarbe: "weiß",
    tootltip_materialfarbe: "weiß",
    farbigkeit: "1/0 Skala",
    tooltip_farbigkeit:
      "1/0. Einseitig einfarbig. Strichmotiv, also keine Verläufe",
    form: "Rechteckig",
    tooltip_form: "Rechteckig mit spitzen Ecken",
    format_breite: 0,
    format_hoehe: 0,
    tooltip_format: "Angaben in mm.",
    traeger: "Auf Bogen",
    tooltip_traeger: "Angestanzt auf handlichen Bögen",
    klebehaftung: "Festhaftend",
    tooltip_klebehaftung:
      "Gerne bemustern wir Ihnen das gewünschte Material zum Testen der Klebehaftung",
    lieferland: "Deutschland",
    liefertermin: "1.1.1970",
    tooltip_liefertermin:
      "Kann auf Inseln abweichen. Sprechen Sie uns ggf. auf einne schnelleren Termin direkt an.",
    sorten: 1,
    auflage: 0,
    price_net: 0.0,
    price_gross: 0.0,
    image_calc_url: "/images/stickers/screenprintstickers.webp",
    quantity: 1,
  },
  {
    id: 2,
    nickname: "Rollenaufkleber",
    tooltip_nickname: "Roll It like the Stones",
    drucktechnik: "Flexodruck",
    tooltip_drucktechnik: "",
    bedruckstoff: "PE-Folie",
    tooltip_bedruckstoff: "PE-Folie",
    materialfarbe: "weiß",
    tootltip_materialfarbe: "weiß",
    farbigkeit: "1/0 Skala",
    tooltip_farbigkeit:
      "1/0. Einseitig einfarbig. Strichmotiv, also keine Verläufe",
    form: "Rechteckig",
    tooltip_form: "Rechteckig mit spitzen Ecken",
    format_breite: 0,
    format_hoehe: 0,
    tooltip_format: "Angaben in mm.",
    traeger: "Auf Bogen",
    tooltip_traeger: "Angestanzt auf handlichen Bögen",
    klebehaftung: "Festhaftend",
    tooltip_klebehaftung:
      "Gerne bemustern wir Ihnen das gewünschte Material zum Testen der Klebehaftung",
    lieferland: "Deutschland",
    liefertermin: "1.1.1970",
    tooltip_liefertermin:
      "Kann auf Inseln abweichen. Sprechen Sie uns ggf. auf einne schnelleren Termin direkt an.",
    sorten: 1,
    auflage: 0,
    price_net: 0.0,
    price_gross: 0.0,
    image_calc_url: "/images/stickers/rollenetiketten.webp",
    quantity: 1,
  },
]);
